Update sdkAutomation.yaml

diff --git a/.github/workflows/sdkAutomation.yaml b/.github/workflows/sdkAutomation.yaml
--- a/.github/workflows/sdkAutomation.yaml
+++ b/.github/workflows/sdkAutomation.yaml
@@ -138,110 +138,110 @@ jobs:
         gh release download --repo 'MikroElektronika/sdk_automation' --pattern 'extracted_${{ steps.upper-mcu-name.outputs.mcu_name }}.zip'
         echo "exit_code=$?" >> $GITHUB_OUTPUT
 
-    - name: print step res
-      if: steps.check-asset-existence.outcome == 'success'
+    - name: Verify if assets were found
+      if: steps.check-asset-existence.outcome != 'success'
       run: |
-        echo "Success!
+        echo "Generated files not found. Starting generation workflow."
 
-      # run: |
-        # prevStep=${{ steps.check-asset-existence.outputs.exit_code }}
-        # echo "Result of previous step: "
-        # echo $prevStep
     
-    # # Trigger the workflow on the private repository (Assuming the private repository has a workflow that runs on repository_dispatch event)
-    # - name: Trigger Workflow on Private Repository
-    #   env:
-    #     REPO: "MikroElektronika/sdk_automation"
-    #   run: |
-    #     curl -s \
-    #       -X POST \
-    #       -H "Accept: application/vnd.github+json" \
-    #       -H "Authorization: Bearer ${{ secrets.MIKROE_ACTIONS_KEY }}" \
-    #       -H "X-GitHub-Api-Version: 2022-11-28" \
-    #       https://api.github.com/repos/$REPO/actions/workflows/generate_core.yml/dispatches \
-    #       -d '{
-    #             "ref": "main",
-    #             "inputs": {
-    #               "mcu_name": "${{ github.event.inputs.mcu_name }}",
-    #               "vendor": "${{ github.event.inputs.vendor }}",
-    #               "pdfFile": "${{ github.event.inputs.pdfFile }}",
-    #               "file_list": "${{ github.event.inputs.file_list }}"
-    #             }
-    #           }'
+    # Trigger the workflow on the private repository (Assuming the private repository has a workflow that runs on repository_dispatch event)
+    - name: Trigger Workflow on Private Repository
+      if: steps.check-asset-existence.outcome != 'success'
+      env:
+        REPO: "MikroElektronika/sdk_automation"
+      run: |
+        curl -s \
+          -X POST \
+          -H "Accept: application/vnd.github+json" \
+          -H "Authorization: Bearer ${{ secrets.MIKROE_ACTIONS_KEY }}" \
+          -H "X-GitHub-Api-Version: 2022-11-28" \
+          https://api.github.com/repos/$REPO/actions/workflows/generate_core.yml/dispatches \
+          -d '{
+                "ref": "main",
+                "inputs": {
+                  "mcu_name": "${{ github.event.inputs.mcu_name }}",
+                  "vendor": "${{ github.event.inputs.vendor }}",
+                  "pdfFile": "${{ github.event.inputs.pdfFile }}",
+                  "file_list": "${{ github.event.inputs.file_list }}"
+                }
+              }'
 
-    # # Wait for workflow start
-    # - name: Wait for start
-    #   run: sleep 5
+    # Wait for workflow start
+    - name: Wait for start
+      if: steps.check-asset-existence.outcome != 'success'
+      run: sleep 5
 
-    # # Get the ID of the run that we just triggered
-    # - name: Get run ID
-    #   id: get_id
-    #   env:
-    #     REPO: "MikroElektronika/sdk_automation"
-    #     GH_TOKEN: ${{ secrets.MIKROE_ACTIONS_KEY }}
-    #   run: |
-    #     while : ; do
-    #       runID=$(gh api \
-    #           -H "Accept: application/vnd.github+json" \
-    #           -H "X-GitHub-Api-Version: 2022-11-28" \
-    #           repos/$REPO/actions/workflows/generate_core.yml/runs \
-    #           --paginate \
-    #           -q '.workflow_runs[] | select(.status == "in_progress") | .id' | head -n 1)
+    # Get the ID of the run that we just triggered
+    - name: Get run ID
+      if: steps.check-asset-existence.outcome != 'success'
+      id: get_id
+      env:
+        REPO: "MikroElektronika/sdk_automation"
+        GH_TOKEN: ${{ secrets.MIKROE_ACTIONS_KEY }}
+      run: |
+        while : ; do
+          runID=$(gh api \
+              -H "Accept: application/vnd.github+json" \
+              -H "X-GitHub-Api-Version: 2022-11-28" \
+              repos/$REPO/actions/workflows/generate_core.yml/runs \
+              --paginate \
+              -q '.workflow_runs[] | select(.status == "in_progress") | .id' | head -n 1)
 
-    #       if [[ -z "$runID" ]]; then
-    #         echo "No in-progress run found yet. Retrying in 10 seconds..."
-    #         sleep 10
-    #         continue
-    #       fi
+          if [[ -z "$runID" ]]; then
+            echo "No in-progress run found yet. Retrying in 10 seconds..."
+            sleep 10
+            continue
+          fi
 
-    #       echo "run_id=$runID" >> $GITHUB_OUTPUT
-    #       echo "Found in-progress workflow with RUN_ID: $run_id"
-    #       break
-    #     done
+          echo "run_id=$runID" >> $GITHUB_OUTPUT
+          echo "Found in-progress workflow with RUN_ID: $run_id"
+          break
+        done
 
-    # # Wait for the workflow to complete
-    # - name: Wait for the Triggered Workflow Finish
-    #   env:
-    #     REPO: "MikroElektronika/sdk_automation"
-    #     GH_TOKEN: ${{ secrets.MIKROE_ACTIONS_KEY }}
-    #   run: |
-    #     while : ; do
-    #       STATUS=$(gh api \
-    #           -H "Accept: application/vnd.github+json" \
-    #           -H "X-GitHub-Api-Version: 2022-11-28" \
-    #           repos/$REPO/actions/runs/${{ steps.get_id.outputs.run_id }} \
-    #           -q '.status')
+    # Wait for the workflow to complete
+    - name: Wait for the Triggered Workflow Finish
+      if: steps.check-asset-existence.outcome != 'success'
+      env:
+        REPO: "MikroElektronika/sdk_automation"
+        GH_TOKEN: ${{ secrets.MIKROE_ACTIONS_KEY }}
+      run: |
+        while : ; do
+          STATUS=$(gh api \
+              -H "Accept: application/vnd.github+json" \
+              -H "X-GitHub-Api-Version: 2022-11-28" \
+              repos/$REPO/actions/runs/${{ steps.get_id.outputs.run_id }} \
+              -q '.status')
 
-    #       CONCLUSION=$(gh api \
-    #           -H "Accept: application/vnd.github+json" \
-    #           -H "X-GitHub-Api-Version: 2022-11-28" \
-    #           repos/$REPO/actions/runs/${{ steps.get_id.outputs.run_id }} \
-    #           -q '.conclusion')
+          CONCLUSION=$(gh api \
+              -H "Accept: application/vnd.github+json" \
+              -H "X-GitHub-Api-Version: 2022-11-28" \
+              repos/$REPO/actions/runs/${{ steps.get_id.outputs.run_id }} \
+              -q '.conclusion')
 
-    #       echo "Workflow status: $STATUS"
+          echo "Workflow status: $STATUS"
 
-    #       if [[ "$STATUS" == "completed" ]]; then
-    #         echo "Workflow completed with conclusion: $CONCLUSION"
-    #         break
-    #       fi
+          if [[ "$STATUS" == "completed" ]]; then
+            echo "Workflow completed with conclusion: $CONCLUSION"
+            break
+          fi
 
-    #       # Wait for a few seconds before checking again
-    #       sleep 10
-    #     done
+          # Wait for a few seconds before checking again
+          sleep 10
+        done
 
-    #     # Check the conclusion and fail the job if the triggered workflow failed
-    #     if [[ "$CONCLUSION" != "success" ]]; then
-    #       echo "Triggered workflow failed with conclusion: $CONCLUSION"
-    #       exit 1
-    #     fi
+        # Check the conclusion and fail the job if the triggered workflow failed
+        if [[ "$CONCLUSION" != "success" ]]; then
+          echo "Triggered workflow failed with conclusion: $CONCLUSION"
+          exit 1
+        fi
 
-    #     echo "Triggered workflow completed successfully!"
+        echo "Triggered workflow completed successfully!"
 
-    # # Aquire the asset that we just generated with the sdk_automation script
-    # - name: Fetch asset
-    #   run: gh release download --repo MikroElektronika/sdk_automation latest --clobber
-    #   env:
-    #     GH_TOKEN: ${{ secrets.MIKROE_ACTIONS_KEY }}
+    # Aquire the asset that we just generated with the sdk_automation script
+    - name: Fetch asset
+      run: gh release download --repo MikroElektronika/sdk_automation latest --clobber
+      env:
+        GH_TOKEN: ${{ secrets.MIKROE_ACTIONS_KEY }}
 
     # Move the asset we just downloaded to automatization and extract it
     - name: Move to the created directory unzip and distribute files
